/**
 * GogoSalon AI Case Study — Data Layer
 * Source: DailyDesk - AI Usage report.xlsx
 * All effort values in Man-Days (MD) unless noted as MM (Man-Months)
 */

const TASKS = [
  {
    id: 1,
    category: "System",
    name: "Feature Flags for Non-Tickets Tab",
    description: "Thêm feature flags để kiểm soát khả năng hiển thị và sử dụng tính năng trên toàn hệ thống",
    aiRole: "BE: Tự động hoá coding task lặp lại (setup flag names, configure blocking logic, tạo API endpoints). FE: Cấu hình visibility từ API response, fix bugs từ QA.",
    effortSaved: 0.50,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 1.5, withAI: 0.75 },
    effortBE: { withoutAI: 1.0, withAI: 0.5 },
    effortTotal: { withoutAI: 2.5, withAI: 1.25 },
    cumulativeTotal: { withoutAI: 2.5, withAI: 1.25 },
    group: "feature"
  },
  {
    id: 2,
    category: "Ticket",
    name: "Quick Exit Tickets",
    description: "Cho phép thoát chế độ chỉnh sửa ticket bằng cách click bên ngoài",
    aiRole: "FE: Fix bugs từ QA, delegate refactor task để giảm performance overhead.",
    effortSaved: 0.50,
    version: "1.1",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.25 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 0.5, withAI: 0.25 },
    cumulativeTotal: { withoutAI: 3.0, withAI: 1.5 },
    group: "feature"
  },
  {
    id: 3,
    category: "Settings Page",
    name: "Update Technician Schedule",
    description: "Làm lại màn Technician Schedule theo yêu cầu mới",
    aiRole: "FE: Plan/chia nhỏ task theo yêu cầu, shard requirements thành các chunk độc lập, delegate UI coding. BE: Thiết kế table structure mới, viết API endpoints theo đề xuất của AI.",
    effortSaved: 0.5333,
    version: "2.0",
    status: "Done",
    effortFE: { withoutAI: 10.0, withAI: 4.0 },
    effortBE: { withoutAI: 10.0, withAI: 3.0 },
    effortTotal: { withoutAI: 15.0, withAI: 7.0 },
    cumulativeTotal: { withoutAI: 18.0, withAI: 8.5 },
    group: "feature"
  },
  {
    id: 4,
    category: "Schedule",
    name: "Appointment Marker and Reference",
    description: "Nâng cao hành vi appointment và ticket trên màn Schedule",
    aiRole: "FE: Plan/chia nhỏ task, shard requirements, delegate UI coding, fix bugs QA. BE: Viết API endpoints theo cấu trúc AI đề xuất.",
    effortSaved: 0.4118,
    version: "2.0",
    status: "Done",
    effortFE: { withoutAI: 5.0, withAI: 3.0 },
    effortBE: { withoutAI: 3.5, withAI: 2.0 },
    effortTotal: { withoutAI: 8.5, withAI: 5.0 },
    cumulativeTotal: { withoutAI: 26.5, withAI: 13.5 },
    group: "feature"
  },
  {
    id: 5,
    category: "SMS",
    name: "SMS Management Service",
    description: "Tạo microservice mới xử lý SMS: queuing, rate-limiting, error handling",
    aiRole: "BE: Tạo microservice mới theo khuyến nghị AI, sửa đổi AWS deployment và CDK hoàn toàn bằng AI, trao đổi qua lại với AI để tìm giải pháp.",
    effortSaved: 0.4667,
    version: "2.1",
    status: "Done",
    effortFE: { withoutAI: 0, withAI: 0 },
    effortBE: { withoutAI: 15.0, withAI: 8.0 },
    effortTotal: { withoutAI: 15.0, withAI: 8.0 },
    cumulativeTotal: { withoutAI: 41.5, withAI: 21.5 },
    group: "feature"
  },
  {
    id: 6,
    category: "Service Duration",
    name: "Service Duration Fix & Start Time Behaviors",
    description: "Nâng cao tính năng Schedule screen",
    aiRole: "FE: Shard tài liệu và tóm tắt cho dev, hỗ trợ phát triển UI và logic, tối ưu hiệu năng và đề xuất cách tiếp cận cụ thể.",
    effortSaved: 0.3571,
    version: "2.1",
    status: "Done",
    effortFE: { withoutAI: 5.0, withAI: 3.0 },
    effortBE: { withoutAI: 2.0, withAI: 1.5 },
    effortTotal: { withoutAI: 7.0, withAI: 4.5 },
    cumulativeTotal: { withoutAI: 48.5, withAI: 26.0 },
    group: "feature"
  },
  {
    id: 7,
    category: "UAT Bug",
    name: "Pressing enter không chuyển focus đến input tiếp theo",
    description: "Lỗi UAT phiên bản 1.0",
    aiRole: "FE: Phân tích hành vi code cũ và đề xuất cho dev để implement.",
    effortSaved: 0.6667,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 0.75, withAI: 0.25 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 0.75, withAI: 0.25 },
    cumulativeTotal: { withoutAI: 49.25, withAI: 26.25 },
    group: "uat-bug"
  },
  {
    id: 8,
    category: "UAT Bug",
    name: "Ticket không đổi màu sau khi unassign technician",
    description: "Lỗi UAT phiên bản 1.0",
    aiRole: "FE: Phân tích git history commit để xác định thay đổi nào ảnh hưởng logic hiện tại và thực hiện fix.",
    effortSaved: 0.30,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.35 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 0.5, withAI: 0.35 },
    cumulativeTotal: { withoutAI: 49.75, withAI: 26.6 },
    group: "uat-bug"
  },
  {
    id: 9,
    category: "UAT Bug",
    name: "Ticket preservation không hoạt động sau khi đóng/reload trình duyệt",
    description: "Bug nghiêm trọng xảy ra ở edge case hiếm gặp",
    aiRole: "FE: Phân tích redux state management hiện tại, refactor logic vừa giữ tính năng cũ, trao đổi qua lại với AI, dev verify và yêu cầu AI hỏi ngược.",
    effortSaved: 0.75,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 2.0, withAI: 0.5 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 2.0, withAI: 0.5 },
    cumulativeTotal: { withoutAI: 51.75, withAI: 27.1 },
    group: "uat-bug"
  },
  {
    id: 10,
    category: "UAT Bug",
    name: "Resize một cột làm tất cả cột thay đổi kích thước",
    description: "Lỗi UAT phiên bản 1.1",
    aiRole: "FE: Đọc và nghiên cứu table library, tóm lược thông tin, giúp dev chọn đúng approach để fix.",
    effortSaved: 0.50,
    version: "1.1",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.25 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 0.5, withAI: 0.25 },
    cumulativeTotal: { withoutAI: 52.25, withAI: 27.35 },
    group: "uat-bug"
  },
  {
    id: 11,
    category: "UAT Bug",
    name: "Column width persistence bug",
    description: "Lỗi UAT phiên bản 1.1",
    aiRole: "FE: Refactor persistence logic theo yêu cầu khách, giúp dev nhận ra phần requirement bị miss.",
    effortSaved: 0.50,
    version: "1.1",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.25 },
    effortBE: { withoutAI: 0.5, withAI: 0.25 },
    effortTotal: { withoutAI: 1.0, withAI: 0.5 },
    cumulativeTotal: { withoutAI: 53.25, withAI: 27.85 },
    group: "uat-bug"
  },
  {
    id: 12,
    category: "UAT Bug",
    name: "Keyboard navigation không nhất quán trong Ticket create/edit",
    description: "Lỗi UAT phiên bản 1.0",
    aiRole: "FE: Giúp dev navigate qua các lớp keyboard navigation phức tạp, refactor code để giảm số dòng cần thiết.",
    effortSaved: 0.50,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 1.0, withAI: 0.5 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 1.0, withAI: 0.5 },
    cumulativeTotal: { withoutAI: 54.25, withAI: 28.35 },
    group: "uat-bug"
  },
  {
    id: 13,
    category: "UAT Bug",
    name: "Ticket không load data mới nhất khi sửa status và technician",
    description: "Lỗi UAT phiên bản 1.1",
    aiRole: "FE: Tự động refactor redux state logic để hỗ trợ data changes khi refetch. Dev vẫn phải check logic và so sánh với UI thủ công.",
    effortSaved: 0.20,
    version: "1.1",
    status: "Done",
    effortFE: { withoutAI: 0.25, withAI: 0.2 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 0.25, withAI: 0.2 },
    cumulativeTotal: { withoutAI: 54.5, withAI: 28.55 },
    group: "uat-bug"
  },
  {
    id: 14,
    category: "UAT Bug",
    name: "Hiện 2 unsaved ticket khi chuyển tab trong lúc đang edit",
    description: "Lỗi UAT phiên bản 1.1",
    aiRole: "FE: Refactor websocket logic khi tích hợp Quick Exit, phân tích tài liệu và xác định phần bị miss khi implement.",
    effortSaved: 0.60,
    version: "1.1",
    status: "Done",
    effortFE: { withoutAI: 0.25, withAI: 0.1 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 0.25, withAI: 0.1 },
    cumulativeTotal: { withoutAI: 54.75, withAI: 28.65 },
    group: "uat-bug"
  },
  {
    id: 15,
    category: "UAT Bug",
    name: "Ticket screen Performance issue",
    description: "Tối ưu hiệu năng render table, hotfix production",
    aiRole: "FE: Delegate và nghiên cứu cùng AI cách tối ưu-refactor components, AI làm coding, dev chỉ review.",
    effortSaved: 0.5833,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 3.0, withAI: 1.25 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 3.0, withAI: 1.25 },
    cumulativeTotal: { withoutAI: 57.75, withAI: 29.9 },
    group: "uat-bug"
  },
  {
    id: 16,
    category: "UAT Bug",
    name: "Không focus cell được chọn khi single click",
    description: "Lỗi UAT phiên bản 1.2",
    aiRole: "FE: Giúp dev navigate qua cấu trúc component phức tạp để tìm root cause và implement fix (fix lặp lại ~20 components).",
    effortSaved: 0.75,
    version: "1.2",
    status: "Done",
    effortFE: { withoutAI: 1.0, withAI: 0.25 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 1.0, withAI: 0.25 },
    cumulativeTotal: { withoutAI: 58.75, withAI: 30.15 },
    group: "uat-bug"
  },
  {
    id: 17,
    category: "UAT Bug",
    name: "Submit & Print hiển thị sai Appointment",
    description: "Bug trong logic in ấn",
    aiRole: "FE: Refactor logic printing phức tạp, xác định root cause, viết báo cáo chi tiết cho khách, điều hướng AI agents để coding.",
    effortSaved: 0.85,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 2.0, withAI: 0.3 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 2.0, withAI: 0.3 },
    cumulativeTotal: { withoutAI: 60.75, withAI: 30.45 },
    group: "uat-bug"
  },
  {
    id: 18,
    category: "UAT Bug",
    name: "Submit & Print không hiển thị technician đã chọn",
    description: "Bug trong chế độ view khi Cancel/Print",
    aiRole: "FE: Tương tự task #17, dùng AI để refactor và fix logic printing.",
    effortSaved: 0.85,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 1.0, withAI: 0.15 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 1.0, withAI: 0.15 },
    cumulativeTotal: { withoutAI: 61.75, withAI: 30.6 },
    group: "uat-bug"
  },
  {
    id: 19,
    category: "UAT Bug",
    name: "Xoá ticket đầu tiên làm ticket split hiển thị ID NaN",
    description: "Bug trong logic split tickets",
    aiRole: "BE: Refactor ticket splitting logic và websocket implementation hoàn toàn bằng AI, orchestrate AI Agents để fix, tạo PR và deploy.",
    effortSaved: 0.70,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.15 },
    effortBE: { withoutAI: 0.5, withAI: 0.15 },
    effortTotal: { withoutAI: 1.0, withAI: 0.3 },
    cumulativeTotal: { withoutAI: 62.75, withAI: 30.9 },
    group: "uat-bug"
  },
  {
    id: 20,
    category: "UAT Bug",
    name: "Split Tickets hiển thị undefined ID khi split ticket mới",
    description: "Bug trong logic split tickets",
    aiRole: "BE: Tương tự task #19, AI xử lý toàn bộ logic splitting.",
    effortSaved: 0.70,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.15 },
    effortBE: { withoutAI: 0.5, withAI: 0.15 },
    effortTotal: { withoutAI: 1.0, withAI: 0.3 },
    cumulativeTotal: { withoutAI: 63.75, withAI: 31.2 },
    group: "uat-bug"
  },
  {
    id: 21,
    category: "UAT Bug",
    name: "Quick Exit không hoạt động khi user khác submit ticket",
    description: "Bug trong websocket event handling",
    aiRole: "FE: Sửa websocket event nhanh, giúp dev navigate đến component chính. BE: Điều chỉnh websocket connection và data structure phức tạp để đơn giản hoá logic.",
    effortSaved: 0.70,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 0.5, withAI: 0.25 },
    effortBE: { withoutAI: 1.0, withAI: 0.2 },
    effortTotal: { withoutAI: 1.5, withAI: 0.45 },
    cumulativeTotal: { withoutAI: 65.25, withAI: 31.65 },
    group: "uat-bug"
  },
  {
    id: 22,
    category: "UAT Bug",
    name: "Sửa ticket ngày khác bị áp dụng vào ticket ngày hiện tại",
    description: "Bug logic timezone",
    aiRole: "FE + BE: Dùng AI để điều chỉnh timezone logic trong codebase.",
    effortSaved: 0.85,
    version: "1.0",
    status: "Done",
    effortFE: { withoutAI: 3.0, withAI: 0.45 },
    effortBE: { withoutAI: 0, withAI: 0 },
    effortTotal: { withoutAI: 3.0, withAI: 0.45 },
    cumulativeTotal: { withoutAI: 68.25, withAI: 32.1 },
    group: "uat-bug"
  }
];

const SUMMARY = {
  totalMDWithoutAI: 68.25,
  totalMDWithAI: 32.1,
  totalMMWithoutAI: 3.6625,
  totalMMWithAI: 1.605,
  mmSaved: 2.0575,
  percentSaved: 0.5618,
  totalTasks: 22,
  projectTotalMM: 17.62,
  teamSize: 6,
  teamBreakdown: "2 FE, 2 BE, 1 QC, 1 BA"
};

const ADOPTION = {
  totalFunctions: 30,
  usingAI: 14,
  notUsingAI: 16,
  reasons: [
    { reason: "Không cần thiết (task đơn giản)", count: 2 },
    { reason: "Dev chưa quen sử dụng AI", count: 1 },
    { reason: "Không ghi nhận lý do cụ thể", count: 13 }
  ]
};
